import 'dart:convert';
import 'dart:io';

import '../models/generated_contracts.dart';

const String kSetupDoctorExportPathEnv = 'GUI_SHELL_SETUP_DOCTOR_EXPORT_JSON';
const String kSetupDoctorContextPathEnv = 'GUI_SHELL_SETUP_DOCTOR_CONTEXT_JSON';

const List<String> kRequiredSetupDoctorCheckIds = [
  'windows.installed_app_path',
  'windows.artifact_hash',
  'first_run.config_created',
  'first_run.audit_dir_writable',
  'setup_doctor.ran_from_installed_app_path',
  'setup_doctor.runtime_connection',
  'setup_doctor.authority_boundary',
  'setup_doctor.network_public_bind',
  'setup_doctor.recovery_instruction',
  'setup_doctor.audit_storage',
];

Future<void> writeSetupDoctorProductExportIfRequested(
  ShellSnapshot snapshot, {
  Map<String, String>? environment,
  String? resolvedExecutable,
}) async {
  final env = environment ?? Platform.environment;
  final exportPath = env[kSetupDoctorExportPathEnv];
  if (exportPath == null || exportPath.trim().isEmpty) {
    return;
  }

  final context = _loadContext(env[kSetupDoctorContextPathEnv]);
  await _ensureInstalledFirstRunConfig(context);
  final report = buildSetupDoctorProductExport(
    snapshot,
    command: resolvedExecutable ?? Platform.resolvedExecutable,
    context: context,
  );
  final output = File(exportPath);
  await output.parent.create(recursive: true);
  await output.writeAsString(
    const JsonEncoder.withIndent('  ').convert(report),
  );
}

Future<void> _ensureInstalledFirstRunConfig(
    Map<String, Object?> context) async {
  final configPath = _stringValue(context['config_path']);
  if (configPath.isEmpty) {
    return;
  }
  final configFile = File(configPath);
  if (await configFile.exists()) {
    return;
  }
  await configFile.parent.create(recursive: true);
  final config = <String, Object?>{
    'schema_version': 1,
    'created_by': 'gui_shell_desktop_installed_first_run',
    'created_at': DateTime.now().toUtc().toIso8601String(),
    'installer_grants_authority': false,
    'installer_silently_approves_permissions': false,
  };
  await configFile.writeAsString(
    const JsonEncoder.withIndent('  ').convert(config),
  );
}

Map<String, Object?> buildSetupDoctorProductExport(
  ShellSnapshot snapshot, {
  required String command,
  Map<String, Object?> context = const {},
}) {
  final installedAppPath = _stringValue(context['installed_app_path']);
  final installedPathConfirmed =
      _boolValue(context['installed_app_path_confirmed']) &&
          _samePathOrEmpty(command, installedAppPath);
  final artifactHash = _stringValue(context['app_artifact_sha256']);
  final configProbe = _probeConfigJson(_stringValue(context['config_path']));
  final auditProbe = _probeAuditDir(_stringValue(context['audit_dir']));
  final brokerIpcReady = _snapshotCheckPassed(snapshot, 'broker.ipc');
  final brokerPersistenceReady =
      _snapshotCheckPassed(snapshot, 'broker.persistence');
  final brokerReady = snapshot.snapshotSource == 'broker' &&
      brokerIpcReady &&
      brokerPersistenceReady;
  final restrictedBind =
      snapshot.networkExposure.toLowerCase().contains('127.0.0.1') ||
          _boolValue(context['restricted_loopback_bind']);

  final checks = [
    _check(
      'windows.installed_app_path',
      installedPathConfirmed,
      installedPathConfirmed
          ? 'Installed GUI Shell executable launched from $command.'
          : 'Installed executable path was not confirmed by product context.',
      'Launch the installed GUI Shell executable from the isolated staged install root.',
    ),
    _check(
      'windows.artifact_hash',
      artifactHash.startsWith('sha256:'),
      artifactHash.startsWith('sha256:')
          ? 'Installed executable sha256 is $artifactHash.'
          : 'Installed executable sha256 was not supplied to the product export context.',
      'Measure the installed executable hash in the staged run and pass it to the product export context.',
    ),
    _check(
      'first_run.config_created',
      configProbe.ok,
      configProbe.message,
      'Launch the installed app once with an isolated config path and verify the JSON parses.',
    ),
    _check(
      'first_run.audit_dir_writable',
      auditProbe.ok,
      auditProbe.message,
      'Use an isolated audit directory writable by the current Windows user.',
    ),
    _check(
      'setup_doctor.ran_from_installed_app_path',
      installedPathConfirmed,
      installedPathConfirmed
          ? 'Setup Doctor export was generated by the installed app process.'
          : 'Setup Doctor export path was requested, but installed app provenance was not confirmed.',
      'Generate this JSON from the installed Flutter executable, not from an external probe script.',
    ),
    _check(
      'setup_doctor.runtime_connection',
      brokerReady,
      brokerReady
          ? 'Installed app connected to authenticated broker IPC with durable persistence ready.'
          : 'Installed app did not confirm ready broker IPC and durable persistence.',
      'Start the installed Rust broker and launch the app with GUI_SHELL_BROKER_ENDPOINT_JSON.',
    ),
    _check(
      'setup_doctor.authority_boundary',
      !snapshot.installerGrantsAuthority &&
          !snapshot.installerSilentlyApprovesPermissions,
      'Setup Doctor export does not grant authority or silently approve permissions.',
      'Keep Setup Doctor diagnostics non-authoritative and broker-mediated.',
    ),
    _check(
      'setup_doctor.network_public_bind',
      restrictedBind,
      restrictedBind
          ? 'Broker exposure is restricted to loopback.'
          : 'Restricted loopback bind was not confirmed by product state.',
      'Bind the broker endpoint to 127.0.0.1 and rerun the installed evidence collector.',
    ),
    _check(
      'setup_doctor.recovery_instruction',
      true,
      'Every Setup Doctor check includes an operator recovery instruction.',
      'Keep every Setup Doctor check paired with a recovery instruction.',
    ),
    _check(
      'setup_doctor.audit_storage',
      auditProbe.ok,
      auditProbe.message,
      'Repair isolated audit storage before collecting release evidence.',
    ),
  ];

  return {
    'status':
        checks.every((check) => check['status'] == 'pass') ? 'pass' : 'warning',
    'formal_product_evidence': true,
    'evidence_source': {
      'source_kind': 'installed_app_machine_readable_export',
      'product_generated': true,
      'collector_derives_checks': false,
      'synthetic': false,
      'command': command,
      'context_path': _stringValue(context['context_path']),
    },
    'ran_from_installed_app_path': installedPathConfirmed,
    'operator_readable': true,
    'installer_grants_authority': false,
    'installer_silently_approves_permissions': false,
    'snapshot_source': snapshot.snapshotSource,
    'snapshot_generated_at': snapshot.snapshotGeneratedAt,
    'checks': checks,
  };
}

Map<String, Object?> _loadContext(String? path) {
  if (path == null || path.trim().isEmpty) {
    return {};
  }
  final file = File(path);
  if (!file.existsSync()) {
    return {'context_path': path};
  }
  final decoded = jsonDecode(file.readAsStringSync());
  if (decoded is! Map) {
    return {'context_path': path};
  }
  return {
    ...Map<String, Object?>.from(decoded),
    'context_path': path,
  };
}

Map<String, Object?> _check(
  String checkId,
  bool passed,
  String message,
  String recoveryInstruction,
) {
  return {
    'check_id': checkId,
    'status': passed ? 'pass' : 'warning',
    'message': message,
    'recovery_instruction': recoveryInstruction,
    'grants_authority': false,
  };
}

bool _snapshotCheckPassed(ShellSnapshot snapshot, String checkId) {
  for (final check in snapshot.setupDoctorChecks) {
    if (check.checkId == checkId && check.status == 'pass') {
      return true;
    }
  }
  return false;
}

_ProbeResult _probeConfigJson(String path) {
  if (path.isEmpty) {
    return const _ProbeResult(
      false,
      'No config path was supplied to the product export context.',
    );
  }
  try {
    final file = File(path);
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is Map) {
      return _ProbeResult(true, 'Config JSON parsed at $path.');
    }
    return _ProbeResult(
      false,
      'Config file did not contain a JSON object at $path.',
    );
  } catch (error) {
    return _ProbeResult(false, 'Config JSON was not readable at $path: $error');
  }
}

_ProbeResult _probeAuditDir(String path) {
  if (path.isEmpty) {
    return const _ProbeResult(
      false,
      'No audit directory was supplied to the product export context.',
    );
  }
  try {
    final directory = Directory(path)..createSync(recursive: true);
    final probe = File(
      '${directory.path}${Platform.pathSeparator}.gui-shell-setup-doctor-probe',
    );
    probe.writeAsStringSync('ok');
    final readOk = probe.readAsStringSync().trim() == 'ok';
    probe.deleteSync();
    final deleteOk = !probe.existsSync();
    return _ProbeResult(
      readOk && deleteOk,
      readOk && deleteOk
          ? 'Audit directory write/read/delete probe passed at $path.'
          : 'Audit directory probe did not complete at $path.',
    );
  } catch (error) {
    return _ProbeResult(false, 'Audit directory probe failed at $path: $error');
  }
}

bool _samePathOrEmpty(String command, String installedAppPath) {
  if (command.trim().isEmpty || installedAppPath.trim().isEmpty) {
    return false;
  }
  final normalizedCommand = command.replaceAll('/', r'\').toLowerCase();
  final normalizedInstalled =
      installedAppPath.replaceAll('/', r'\').toLowerCase();
  return normalizedCommand == normalizedInstalled;
}

String _stringValue(Object? value) => value == null ? '' : value.toString();

bool _boolValue(Object? value) {
  if (value is bool) {
    return value;
  }
  if (value is String) {
    return value.toLowerCase() == 'true' || value.toLowerCase() == 'yes';
  }
  return false;
}

class _ProbeResult {
  const _ProbeResult(this.ok, this.message);

  final bool ok;
  final String message;
}
